config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  devise_for :my_users
  devise_for :users
  devise_for :models
  root to: 'static_pages#index'

  get 'about', to: 'static_pages#about'

  resources :users
  get 'users/new'

end

app/models/model.rb
class Model < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/my_user.rb
class MyUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :username
  end
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = 'Modus'
		if page_title.empty?
			base_title
		else
			base_title + " | " + page_title
		end
	end

	def menu_active_make(title_content = '')
		script = ''
		if !title_content.empty?
			script += 'jQuery(".menu_bar ul.nav > li").each(function(){'
			script += 'jQuery(this).removeClass("active");'
			script += 'if(jQuery(this).children("a").text() =="' + title_content + '"){' 	
			script += 'jQuery(this).addClass("active");'
			script +=	'}});'
		end
		script
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top menu_bar">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "MODUSversus", root_path, class: "navbar-brand", id: "home" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
   	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class='active'><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <li><%= link_to "Services", '#' %></li>
        <li class="dropdown">
        	<%= link_to "#", class: "dropdown-toggle", role: "button", :data => {:toggle => "dropdown"}, :aria => {:haspopup => "true", :expanded => "false"} do %>
					  Portfolio<span class="caret"></span>
					<% end %>
          <ul class="dropdown-menu">
            <li><%= link_to "Portfolio 2 column pages", "#"%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Portfolio 2 column pages", "#"%></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Portfolio 2 column pages", "#"%></li>
          </ul>
        </li>
        <li><%= link_to "Blog", "#"%></li>
        <li><%= link_to "Features", "#"%></li>
        <li><%= link_to "Contacts", "#"%></li>
        <li class="dropdown">
        	<%= link_to "#", class: "dropdown-toggle", role: "button", :data => {:toggle => "dropdown"}, :aria => {:haspopup => "true", :expanded => "false"} do %>
					  <span id="search_icon" class="glyphicon glyphicon-search" aria-hidden="true"></span>
					<% end %>
          <ul class="dropdown-menu">
            <li>
            	<%= form_tag("#", method: "post", class: "navbar-form navbar-left search_form", role: "search") do %>
	            	<%= content_tag :div, class: "form-group" do -%>
								  <%= text_field_tag 'search', nil, class: 'form-control', placeholder: 'Search' %>
								<% end -%>
							<% end %>
	      		</li>
          </ul>
        </li>
        <li></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>
<div class='clearfix' style='margin-bottom: 80px;'></div>
<% if notice %>
  <p class="alert alert-success"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert alert-danger"><%= alert %></p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
	<head>
	  <title><%= full_title(yield(:title)) %></title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>

	<body>
		<%= render 'layouts/header' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
		<script>
		<%= raw menu_active_make(yield(:title)) %>
		</script>
	</body>

</html>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/index.html.erb
<section id="owl-slider" class="owl-carousel owl-theme">
	<%= content_tag :div, class: "item" do -%>
		<%= image_tag("fullimage1.jpg", alt: "The Last of us") %>
	<% end -%>
	<%= content_tag :div, class: "item" do -%>
		<%= image_tag("fullimage2.jpg", alt: "GTA V") %>
	<% end -%>
	<%= content_tag :div, class: "item" do -%>
		<%= image_tag("fullimage3.jpg", alt: "Mirror Edge") %>
	<% end -%>
</section>

<section class='intro'>
	<div class='container'>
		<div class='intro_row'>
			<div class='col-sm-9 col-xs-12 vcenter'>
				<div class='content'>
						<h2>Some of our top services</h2>
						<p>Ut eleifend libero sed neque rhoncus consequat. Maecenas tincidunt, augue et rutrum condimentum, libero lectus mattis orci, ut commodo. </p>
					</div>
			</div><!-- 
			--><div class='col-sm-3 col-xs-12 text-center vcenter'>
				<div class='content'>
					<button type="button" class="btn btn-danger" aria-haspopup="true" aria-expanded="false">
				    View More
				  </button>
				</div>
			</div>
			<div class='clearfix'></div>
		</div>
	</div>
</section>

<section class='services container'>
	<div class='row'>
		<div class='col-md-3 col-sm-6 text-center'>
			<div class='col col-1'>
				<h3>SUSPENDISSE</h3>
				<p>Quisque id tellus quis risus vehicula vehicula ut turpis. In eros nulla, placerat vitae at, vehicula ut nunc.</p>
				<button type="button" class="btn btn-default" aria-haspopup="true" aria-expanded="false">
			    View More
			  </button>
			</div>
		</div>
		<div class='col-md-3 col-sm-6 text-center'>
			<div class='col col-2'>
				<h3>MAECENAS</h3>
				<p>Ut eleifend libero sed neque rhoncus consequat. Maecenas tincidunt, augue et rutrum condimentum, libero lectus mattis orci, ut commodo.</p>
				<button type="button" class="btn btn-danger" aria-haspopup="true" aria-expanded="false">
			    View More
			  </button>
			</div>
		</div>
		<div class='col-md-3 col-sm-6 text-center'>
			<div class='col col-3'>
				<h3>ALIQUAM</h3>
				<p>Vivamus eget ante bibendum arcu vehicula ultricies. Integer venenatis mattis nisl, vitae pulvinar dui tempor non.</p>
				<button type="button" class="btn btn-danger" aria-haspopup="true" aria-expanded="false">
			    View More
			  </button>
			</div>
		</div>
		<div class='col-md-3 col-sm-6 text-center'>
			<div class='col col-4'>
				<h3>HABITASSE</h3>
				<p>Astehicula ultricies. Integer venenatis mattis nisl, vitae pulvinar dui tempor non.</p>
				<button type="button" class="btn btn-danger" aria-haspopup="true" aria-expanded="false">
			    View More
			  </button>
			</div>
		</div>
	</div>
</section>

<section class='about'>
	<section class='heading'>
		<div class='container'>
			<div class='row content'>
				<div class='col-md-12 text-center'>
					<h1>WHY MODUS VERSUS?</h1>
					<p>Capacitance cascading integer reflective interface data development high bus cache dithering transponder.</p>
				</div>
			</div>
			<div class='row slider'>
				<div class='col-md-4 slider_1'>
					<div class='slider-wrapper'>
						<div class='slider-1'>
							<ul class="slides">
						    <%= content_tag :li do -%>
									<%= image_tag("fullimage1.jpg", alt: "The Last of us") %>
								<% end -%>
								<%= content_tag :li do -%>
									<%= image_tag("fullimage2.jpg", alt: "GTA V") %>
								<% end -%>
								<%= content_tag :li do -%>
									<%= image_tag("fullimage3.jpg", alt: "Mirror Edge") %>
								<% end -%>
						  </ul>
						</div>
					</div>
				</div>
				<div class='col-md-6 col-md-offset-3 slider_2'>
					<div class='slider-wrapper'>
						<div class='slider-2'>
							<ul class="slides">
						    <%= content_tag :li do -%>
									<%= image_tag("fullimage1.jpg", alt: "The Last of us") %>
								<% end -%>
								<%= content_tag :li do -%>
									<%= image_tag("fullimage2.jpg", alt: "GTA V") %>
								<% end -%>
								<%= content_tag :li do -%>
									<%= image_tag("fullimage3.jpg", alt: "Mirror Edge") %>
								<% end -%>
						  </ul>
						</div>
					</div>
				</div>
				<div class='col-md-4 col-md-offset-8 slider_3'>
					<div class='slider-wrapper'>
						<div class='slider-3'>
							<ul class="slides">
						    <%= content_tag :li do -%>
									<%= image_tag("fullimage1.jpg", alt: "The Last of us") %>
								<% end -%>
								<%= content_tag :li do -%>
									<%= image_tag("fullimage2.jpg", alt: "GTA V") %>
								<% end -%>
								<%= content_tag :li do -%>
									<%= image_tag("fullimage3.jpg", alt: "Mirror Edge") %>
								<% end -%>
						  </ul>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>

	<section class='about_content'>
		<div class='container'>
			<div class='row'>
				<section class='col-md-3 why_choose'>
					<h3>Why Choose Us?</h3>
					<div class='reason'>
						<ul>
							<li>Quisque at massa ipsum</li>
							<li>Maecenas a lorem augue, egestas</li>
							<li>Cras vitae felis at lacus eleifend</li>
							<li>Etiam auctor diam pellentesque</li>
							<li>Nulla ac massa at dolor</li>
							<li>Condimentum eleifend vitae vitae</li>
						</ul>
					</div>
				</section>
				<section class='col-md-6 skills'>
					<p>Curabitur quis nisl in leo euismod venenatis eu in diam. Etiam auctor diam pellentesque lectus <a href=''>vehicula mattis</a>. Nulla ac massa at dolor condimentum eleifend vitae vitae urna.</p>
					<div class='graph row'>
						<div class='col-md-3'>

						</div>

					</div>
				</section>
				<section class='col-md-3 testemoials'>
					<h3>What Client’s Say?</h3>
					<div class='say_content'>
						<p class='say'>Curabitur quis nisl in leo euismod venenatis eu in diam. Etiam auctor diam pellentesque lectus vehicula mattis. Nulla ac massa at dolor condimentum</p>
						<p class='user_name'>Jone Doe</p>
					</div>
				</section>
			</div>
		</div>
	</sectioin>
</section>

<section class='clients'>
	<div class='container'>
		<div class='row'>
			<div class='col-md-12'>
				<div id="clients_slider">
				  <ul class="slides">
				    <%= content_tag :li do -%>
							<%= image_tag("fullimage1.jpg", alt: "The Last of us") %>
						<% end -%>
						<%= content_tag :li do -%>
							<%= image_tag("fullimage2.jpg", alt: "GTA V") %>
						<% end -%>
						<%= content_tag :li do -%>
							<%= image_tag("fullimage3.jpg", alt: "Mirror Edge") %>
						<% end -%>
				  </ul>
				</div>
			</div>
		</div>
	</div>
</section>

app/views/users/new.html.erb
<section class='container'>
	<div class="row">
	  <div class="col-md-6 col-md-offset-3">
			<%= form_for(@user) do |f| %>
				<%= f.label :name %>
				<%= f.text_field :name %>

				<%= f.label :email %>
				<%= f.text_field :email %>

				<%= f.label :password %>
				<%= f.password_field :password %>

				<%= f.label :password_confirmation, "Confirmation" %>
				<%= f.password_field :password_confirmation %>

				<%= f.submit "Create My Account", class: "btn btn-primary" %>
			<% end %>
		</div>
	</div>
</section>

app/views/users/show.html.erb
<%= @user.name %>
<%= @user.email %>